### ISSUE TITLE
[Feature request] Add --language=none 

### ISSUE THREAD

**Issue by metita** [Abu3safeer/crunchyroll-dl-gui#1]
I am using this GUI a lot, would be amazing if you add "--language=none" as a Language option to test `softsub` functionality as I am not fan of Command Lines.

**Comment by Abu3safeer** [comment]
Working on it.

**Comment by Abu3safeer** [comment]
It will take some time until update finish
![image](https://user-images.githubusercontent.com/12091003/57158333-d8969480-6deb-11e9-89ae-15724d80f4b0.png)

**Comment by metita** [comment]
Thanks :)

**Comment by Abu3safeer** [comment]
@basuritashka  is it done and ready for download, you can download it now, please report any issues you find, I will try to fix it as soon as possible.

**Comment by metita** [comment]
Okay, thanks, appreciated.
